"""empty message

Revision ID: 2317f17912e6
Revises: 19ff6c01a455
Create Date: 2022-11-05 17:58:49.090537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2317f17912e6'
down_revision = '19ff6c01a455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'birth_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'birth_date',
               existing_type=sa.String(length=100),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
