"""empty message

Revision ID: cd271ed72be2
Revises: 088d496cc125
Create Date: 2022-11-09 20:05:28.068603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd271ed72be2'
down_revision = '088d496cc125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=700),
               existing_nullable=False)
    op.alter_column('event', 'start_day',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('event', 'end_day',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('event', 'geolocation',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('event', 'img_url',
               existing_type=sa.VARCHAR(length=320),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'img_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=320),
               existing_nullable=True)
    op.alter_column('event', 'geolocation',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    op.alter_column('event', 'end_day',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    op.alter_column('event', 'start_day',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    op.alter_column('event', 'description',
               existing_type=sa.String(length=700),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###
