"""empty message

Revision ID: d93fc9616758
Revises: 04753f5b16b2
Create Date: 2022-11-08 00:26:23.036760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd93fc9616758'
down_revision = '04753f5b16b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'content',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=220),
               existing_nullable=False)
    op.alter_column('event', 'img_url',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=320),
               existing_nullable=False)
    op.alter_column('rating', 'rate',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=5),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rating', 'rate',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)
    op.alter_column('event', 'img_url',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.alter_column('comment', 'content',
               existing_type=sa.String(length=220),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    # ### end Alembic commands ###
