"""empty message

Revision ID: f26f0f893475
Revises: 86c9d32f1253
Create Date: 2022-11-04 23:49:40.672941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f26f0f893475'
down_revision = '86c9d32f1253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_birth_date_key', 'user', type_='unique')
    op.drop_constraint('user_last_name_key', 'user', type_='unique')
    op.drop_constraint('user_name_key', 'user', type_='unique')
    op.drop_constraint('user_phone_key', 'user', type_='unique')
    op.drop_constraint('user_rol_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_rol_key', 'user', ['rol'])
    op.create_unique_constraint('user_phone_key', 'user', ['phone'])
    op.create_unique_constraint('user_name_key', 'user', ['name'])
    op.create_unique_constraint('user_last_name_key', 'user', ['last_name'])
    op.create_unique_constraint('user_birth_date_key', 'user', ['birth_date'])
    # ### end Alembic commands ###
